config/routes.rb
RentACar::Application.routes.draw do
  resources :cars do
	  resources :bookings
	end
  devise_for :users 
  devise_scope :user do
  	authenticated :user do
    	root :to => "static_pages#home", as: :authenticated_root
  	end
  	unauthenticated :user do
   		root :to => 'devise/sessions#new', as: :unauthenticated_root
  	end
	end
	match "static_pages/search_results", to: "static_pages#search_results", via: "post"
end

app/models/booking.rb
require_relative './concerns/bookable'

class Booking < ActiveRecord::Base
  include Bookable
  def assign_cost  	
  	self.update_attribute(:cost, self.length*self.car.price)
  end
end

app/models/car.rb
class Car < ActiveRecord::Base
	has_many :bookings

	validates :name, :description, :category, :price, presence: true
	validates :name, length: { maximum: 30 }
	validates :description, length: { maximum: 300 }
	validates :category, inclusion: { in: ["A", "B", "C"] }
	validates :price, numericality: { only_integer: true, greater_than: 0 }


	def assign_price
		prices = {	"A" => 100, 
								"B" => 75,
								"C" => 50 }
		self.price = prices[self.category]
	end
end

app/models/concerns/bookable.rb
module Bookable
  extend ActiveSupport::Concern

  included do
    belongs_to :car

    validates :start_time, :client, presence: true 
    validates :length, presence: true, numericality: { greater_than: 0 }
    validate :start_date_cannot_be_in_the_past
    validate :overlaps

    before_validation :calculate_end_time
  

    scope :end_during, ->(new_start_time, new_end_time) do
      if (!new_start_time.nil?) && (!new_end_time.nil?)
        where('end_time > ? AND end_time < ?', new_start_time, new_end_time)
      else
        return nil
      end
    end

    scope :start_during, ->(new_start_time, new_end_time) do
      if (!new_start_time.nil?) && (!new_end_time.nil?)
        where('start_time > ? AND start_time < ?', new_start_time, new_end_time)
      else
        return nil
      end
    end

    scope :happening_during, ->(new_start_time, new_end_time) do
      if (!new_start_time.nil?) && (!new_end_time.nil?)
        where('start_time > ? AND end_time < ?', new_start_time, new_end_time)
      else
        return nil
      end 
    end

    scope :enveloping, ->(new_start_time, new_end_time) do
      if (!new_start_time.nil?) && (!new_end_time.nil?)
        where('start_time < ? AND end_time > ?', new_start_time, new_end_time)
      else
        return nil
      end
    end

    scope :identical, ->(new_start_time, new_end_time) do
      if (!new_start_time.nil?) && (!new_end_time.nil?)
        where('start_time = ? AND end_time = ?', new_start_time, new_end_time)
      else
        return nil
      end
    end
  end

  def overlaps
    overlapping_bookings = [ 
      car.bookings.end_during(start_time, end_time),
      car.bookings.start_during(start_time, end_time),
      car.bookings.happening_during(start_time, end_time),
      car.bookings.enveloping(start_time, end_time),
      car.bookings.identical(start_time, end_time)
    ].flatten

    overlapping_bookings.delete self
    if overlapping_bookings.any?
      errors.add(:start_time, 'Slot has already been booked.')
    end
  end

  def check_availability
    overlapping_bookings = [ 
      car.bookings.end_during(start_time, end_time),
      car.bookings.start_during(start_time, end_time),
      car.bookings.happening_during(start_time, end_time),
      car.bookings.enveloping(start_time, end_time),
      car.bookings.identical(start_time, end_time)
    ].flatten

    overlapping_bookings.delete self
    if !overlapping_bookings.any?
      car
    end
  end

  def start_date_cannot_be_in_the_past
    if start_time && start_time < Date.today
      errors.add(:start_time, 'must be today or later')
    end
  end

  def calculate_end_time
    start_time = validate_start_time
    length = validate_length
    if start_time && length
      self.end_time = start_time + length.days
    end
  end


  def as_json(options = {})  
   {  
    :id => self.id,  
    :start => self.start_time,  
    :end => self.end_time,  
    :recurring => false, 
    :allDay => false
   }  
  end 


  private

    def validate_start_time
      if !self.start_time.nil?
        start_time = self.start_time
      else
        return nil
      end
    end

    def validate_length
      if !self.length.nil?
        length = self.length.to_i
      else
        return nil
      end
    end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  respond_to :html, :xml, :json
  before_filter :authenticate_user!
  before_action :find_car

  def index
    @bookings = Booking.where("car_id = ? AND end_time >= ?", @car.id, Time.now).order(:start_time)
    respond_with @bookings
  end

  def create
    @booking =  @car.bookings.create(booking_params)
    @booking.assign_cost
    if @booking.save
      redirect_to car_booking_path(@car, @booking)
    else
      render 'cars/show'
    end
  end

  def show
    @booking = Booking.find(params[:id])
  end

  def destroy
    @booking = Booking.find(params[:id]).destroy
    if @booking.destroy
      flash[:success] = "Booking #{@booking.car.name} by #{@booking.client} has been canceled"
      redirect_to car_path(@car)
    else
      render 'index'
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:start_time, :length, :client, :car_id)
  end

  def save booking
    if @booking.save
        flash[:notice] = 'booking added'
        redirect_to car_booking_path(@car, @booking)
      else
        render 'new'
      end
  end

  def find_car
    if params[:car_id]
      @car = Car.find_by_id(params[:car_id])
    end
  end

end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_filter :authenticate_user!

  def index
    @cars = Car.paginate(page: params[:page], per_page: 5)
  end

  def show
    @car = Car.find(params[:id])
    @booking = @car.bookings.build
  end

  def new
    @car = Car.new
  end

  def create
    @car = Car.create(car_params)
    @car.assign_price
    if @car.save
      name = @car.name
      redirect_to cars_path
      flash[:success] = "#{name} created"
    else
      render 'new'
    end
  end

  def destroy
    @car = Car.find(params[:id])
    @car.destroy
    redirect_to cars_path
  end

  def edit
    @car = Car.find(params[:id])
  end

  def update
    @car = Car.find(params[:id])
    @car.update(car_params)
    @car.assign_price
    if @car.save
      flash[:success] = "Your car was updated succesfully"
      redirect_to cars_path
    else
      render 'edit'
    end
  end

  private
    def car_params
      params.require(:car).permit(:name, :description, :category)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	before_filter :authenticate_user!
	def home		
	end

	def search_results
		@booking = Booking.new(start_time: params[:start_time], length: params[:length])
		@booking.calculate_end_time
		@cars = Car.all
		render :partial => 'search_results', :content_type => 'text/html'	
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/bookings/index.html.erb
<h3> Bookings for <%= @car.name %></h3>  
<% @bookings.each do |booking| %>
  <ul class="listing">
    <li><%= booking.client %></li>
    <li><%= booking.start_time %> - <%= booking.end_time %></li>
  </ul>
  <div class="btn-group">
    <%= link_to "Show", car_booking_path(@car, booking), class: 'btn btn-default btn-sm' %>
    <%= link_to "Cancel", car_booking_path(@car, booking), method: :delete, class: 'btn btn-default btn-sm' %>    
  </div>
<% end %>

app/views/bookings/show.html.erb
<h3>Booking Confirmation</h3>
<hr>
<ul class="listing">
	<li>client: <%= @booking.client %></li>
	<li>car: <%= @booking.car.name %></li>
	<li>from: <%= @booking.start_time %> til: <%= @booking.calculate_end_time %> </li>
	<li>cost: <%= @booking.cost %></li>
</ul>

<div class="container">
	<div class="btn-group">
	<%= link_to "Cancel", car_booking_path(@car, @booking), method: :delete, class: 'btn btn-default' %>
	<%= link_to "Back", car_path(@car), class: 'btn btn-default' %>
	</div>
</div>

app/views/cars/edit.html.erb
<h1>Edit #<%= @car.id %> car</h1>
<%= form_for @car, url: { action: :update } do |f| %>
	<%= render 'shared/errors_messages', object: f.object %>
<div class="form-group">
		<%= f.label :name, class: 'col-md-2 control-label' %>
		<div class="col-md-10">
			<%= f.text_field :name, class: 'form-control' %>
		</div>
	</div>

	<div class="form-group">
		<%= f.label :description, class: 'col-md-2 control-label' %>
		<div class="col-md-10">
			<%= f.text_area :description, class: 'form-control' %>
		</div>
	</div>

	<div class="form-group">	
		<%= f.label :category, class: 'col-md-2 control-label' %>
		<div class="col-md-10">
			<%= f.select :category, ["A", "B", "C"], class: 'form-control' %>
		</div>
	</div>

	<div class="form-group">
		<div class="col-md-offset-2 col-md-10">
			<%= f.submit class: 'btn btn-primary' %>
		</div>
	</div>
<% end %>

app/views/cars/index.html.erb
<% @cars.each do |car| %>
		<h2><%= link_to car.name, car %></h2>
		<ul class="listing">
			<li>category: <%= car.category %></li>
			<li>price per day: <%= car.price %></li>
			<li><%= car.description %></li>
		</ul>
		
		<div class="btn-group">
			<%= link_to "Book it", car_path(car), class: 'btn btn-default btn-sm' %>
			<%= link_to "Edit", edit_car_path(car), class: 'btn btn-default btn-sm'  %>
			<%= link_to "Destroy", car_path(car), method: :delete, class: 'btn btn-default btn-sm'  %>
		</div>
<% end %>
<br>
<%= will_paginate %>

app/views/cars/new.html.erb
<h1>New car</h1>
<%= form_for @car, url: { action: :create } do |f| %>
	<%= render 'shared/errors_messages', object: f.object %>
	
	<div class="form-group">
		<%= f.label :name, class: 'col-md-2 control-label' %>
		<div class="col-md-10">
			<%= f.text_field :name, class: 'form-control' %>
		</div>
	</div>

	<div class="form-group">
		<%= f.label :description, class: 'col-md-2 control-label' %>
		<div class="col-md-10">
			<%= f.text_area :description, class: 'form-control' %>
		</div>
	</div>

	<div class="form-group">	
		<%= f.label :category, class: 'col-md-2 control-label' %>
		<div class="col-md-10">
			<%= f.select :category, ["A", "B", "C"], class: 'form-control' %>
		</div>
	</div>

	<div class="form-group">
		<div class="col-md-offset-2 col-md-10">
			<%= f.submit class: 'btn btn-primary' %>
		</div>
	</div>
<% end %>

app/views/cars/show.html.erb
<div class="container">
	<h2><%= @car.name %></h2>
	<ul class="listing">
		<li>category: <%= @car.category %></li>
		<li>price per day: <%= @car.price %></li>
		<li><%= @car.description %></li>
	</ul>
</div>

<div class="container">
	<div class="btn-group">
		<%= link_to "Edit", edit_car_path(@car), class: 'btn btn-default btn-sm'  %>
		<%= link_to "Destroy", car_path(@car), method: :delete, class: 'btn btn-default btn-sm'  %>
		<%= link_to "Bookings", car_bookings_path(@car), class: "btn btn-default btn-sm" %>
	</div>
</div>
<hr>

<div class="container">
	<h2>Book it</h2>
	<%= render 'shared/booking_form' %>
</div>

<hr>

<div class="calendar_container">
  <div id="calendar">
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
	<div class="container">
		<div class="navbar-header">
			<ul class="nav nav-pills">
				<li><%= link_to "RENT A CAR", authenticated_root_path %>
				<% if user_signed_in? %>
					<li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Cars <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "All cars", cars_path %></li>
              <li><%= link_to "New car", new_car_path %></li>
            </ul>
          </li>
					<li><%= link_to "Account", edit_user_registration_path(current_user) %></li>
					<li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
				<% else %>
					<li><%= link_to "Sign in", new_user_session_path %></li>
					<li><%= link_to "Sign up", new_user_registration_path %></li>
				<% end %>
			</ul>
		</div>
	</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RentACar</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/header' %>
	<div id="main", class="container">
		<% flash.each do |name, msg| -%>
  		<%= content_tag :div, msg, class: "alert alert-#{name}" %>
		<% end -%>
	
		<div id="container", class="col-md-9 center-block">
			<%= yield %>
			
		</div>
	</div>

</body>
</html>

app/views/shared/_booking_form.html.erb
<%= form_for ([@car, @booking]) do |f| %>
  <% if @booking.errors.any? %>
    <div id="error_explanation"> 
      <ul>
      <% @booking.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :client, class: 'col-md-2 control-label' %>
    <div class="col-md-10">    
      <%= f.text_field :client %>
    </div>
  </div>

  <div class="form-group">
  	<%= f.label :start_time, class: 'col-md-2 control-label' %>
  	<div class="col-md-10">    
      <%= f.date_select :start_time, start_year: Date.today.year %>
    </div>
  </div>

  <div class="form-group">
  	<%= f.label :number_of_days, class: 'col-md-2 control-label' %>
  	<div class="col-md-10">    
      <%= f.number_field :length, min: 1 %>
    </div>
  </div>

  <div class="form-group">
  	<div class="col-md-offset-2 col-md-10">
    	<%= f.submit "Book it" %>
    </div>
  </div>
<% end %> 

app/views/shared/_errors_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(object.errors.count, "error") %> prohibited this form from being saved:</h3> 
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/_search_results.html.erb
<hr>
<h3>Available cars</h3>
From <%= @booking.start_time %> till <%= @booking.end_time %>
<% @cars.each do |car| %>
	<% @booking.car = car %>
	<% if available_car = @booking.check_availability %>
		<div class="container">
			<h2><%= link_to available_car.name, car_path(available_car) %></h2>
			<ul class="listing">
				<li>category: <%= available_car.category %></li>
				<li>price per day: <%= available_car.price %></li>
				<li><%= available_car.description %></li>	
			</ul>
		</div>
		<div class="container">
			<div class="btn-group">
				<%= link_to "Book it", car_path(car), class: 'btn btn-default btn-sm'  %>
			</div>
		</div>
	<% end %>
<% end %>

app/views/static_pages/home.html.erb
<h1>Rent a car</h1>
<h5>Check which cars are available</h5>
<hr>

<%= form_tag({action: 'search_results'}, remote: true, :'data-update-target' => 'update-container') do %>	
	<%= label_tag 'Start time' %>
	<%= date_field_tag 'start_time', Date.today(), class: 'textinput', min: Date.today() %>
	<%= label_tag 'Number of days' %>
	<%= number_field_tag 'length', nil, class: 'textinput', min: 1 %>
	<%= submit_tag 'Check it', disable_with: 'Please wait...', class: 'submit' %>
<% end %>

<div id="update-container">
</div>